version: '3'

services:
  db:
    image: postgres:13.1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:1.30.0
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    env_file:
      - .env
    networks:
     - db
     - fusionauth
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

  app:
    build: .
    container_name: express-jwt-fusionauth_app
    depends_on:
      - fusionauth
    environment:
      DEBUG: express-jwt-fusionauth
    env_file:
      - .env
    networks:
     - fusionauth
    ports:
      - 3000:3000

networks:
  db:
    driver: bridge
  fusionauth:
    driver: bridge

volumes:
  db_data:
  fa_config:
