version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.01.1
    resource_class: large

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Start containers and run tests against them
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/mocha/mocha.xml
      - store_artifacts:
          path: coverage
      - run:
          name: Upload to coveralls
          command: |
            npm install -g coveralls
            export COVERALLS_ENDPOINT=https://coveralls.io
            cat ./coverage/lcov.info | coveralls
