version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:fermium

    working_directory: ~/repo

    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - checkout

      - run:
          name: Start containers and run tests against them
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/mocha/mocha.xml
      - store_artifacts:
          path: coverage
      - coveralls/upload
