version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Start containers and run tests against them
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/mocha/mocha.xml
      - store_artifacts:
          path: coverage
      - coveralls/upload
